/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.Dado;
import dados.DadosTurma;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Turma;

/**
 *
 * @author jadson
 */
public class GuiInscricaoTurma extends javax.swing.JFrame 
{
    /**
     * Creates new form GuiInscricaoTurma
     */
    private static Aluno aluno;
    
    public GuiInscricaoTurma(Aluno a) 
    {
        initComponents();
        aluno = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInscricao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTurma = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inscrição Turma");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInscricao.setText("Inscrever");
        btnInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscricaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Turmas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 6, -1, -1));

        tblTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Curso", "Professor", "Disciplina"
            }
        ));
        jScrollPane2.setViewportView(tblTurma);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 41, 393, 165));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscricaoActionPerformed
        // Inscrever o aluno em uma turma selecionada
        Turma turma = (Turma) tblTurma.getValueAt(tblTurma.getSelectedRow(), 0);
        Turma turma2 = turma;
        Dado d = new DadosTurma();
        try 
        {
            d.excluir(turma);
            
            turma2.addAluno(GuiInscricaoTurma.aluno);
            d.incluir(turma2);
            
            JOptionPane.showMessageDialog(null,"Você foi inscrito na turma");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(GuiInscricaoTurma.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnInscricaoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try 
        {
            // TODO add your handling code here:
            preencherTabela();
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(GuiInscricaoTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated
    
    public void preencherTabela() throws Exception 
    {
        List<Turma> turmas = new DadosTurma().listar();
        DefaultTableModel tblTurmas = (DefaultTableModel) tblTurma.getModel();
        int linhas = tblTurmas.getRowCount();
        for(int i=0;i<linhas;i++)
        {
            tblTurmas.removeRow(0);
        }
        for (Turma t: turmas)
        {
            Object linha[] = {t,t.getCurso(),t.getProfessor(),t.getDisciplina(),t.getFinalizado()};
            tblTurmas.addRow(linha);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInscricaoTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInscricaoTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInscricaoTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInscricaoTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new GuiInscricaoTurma(aluno).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscricao;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTurma;
    // End of variables declaration//GEN-END:variables
}
