/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.Dado;
import dados.DadosCurso;
import dados.DadosProfessor;
import dados.DadosUsuario;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Curso;
import model.Formacao;
import model.Professor;
import model.Telefone;
import model.TipoUsuario;
import model.Usuario;

/**
 *
 * @author jadson
 */
public class GuiProfessor extends javax.swing.JDialog
{
    /**
     * Creates new form GuiProfessor
     * @param parent
     * @param modal
     */
    public GuiProfessor(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();        
        loadCb();
    }

    private void loadCb() 
    {
        cboFormacao.setModel(new DefaultComboBoxModel<>(Formacao.values()));
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtEndereco = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        BtnGravarProfessor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboFormacao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxtTelefone1 = new javax.swing.JTextField();
        TxtDDD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboUsuarios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Turma");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, -1));

        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, -1, -1));
        getContentPane().add(TxtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 176, 260, -1));
        getContentPane().add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 260, -1));

        BtnGravarProfessor.setText("Gravar");
        BtnGravarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGravarProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 363, -1, -1));

        jLabel5.setText("Formação");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 221, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Criar Professor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 25, -1, -1));

        cboFormacao.setToolTipText("");
        cboFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFormacaoActionPerformed(evt);
            }
        });
        getContentPane().add(cboFormacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 249, 110, -1));

        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 221, -1, -1));
        getContentPane().add(TxtTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 248, 102, -1));

        TxtDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDDDActionPerformed(evt);
            }
        });
        getContentPane().add(TxtDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 248, 36, -1));

        jLabel8.setText("Usuário");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 293, -1, -1));

        cboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(cboUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, 260, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:               
        cboUsuarios.removeAllItems();
        
        try 
        {
            List<Usuario> usuarios = new DadosUsuario().listar();
            for (Usuario usuario: usuarios)
            {
                if(usuario.getTipo().equals(TipoUsuario.Professor))
                {
                    cboUsuarios.addItem(usuario);
                }
            }            
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(GuiTurmas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_formWindowActivated

    private void BtnGravarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarProfessorActionPerformed
        // TODO add your handling code here:
        Professor professor = new Professor ((Formacao) cboFormacao.getModel().getSelectedItem(), (Usuario) cboUsuarios.getModel().getSelectedItem(), TxtNome.getText(),TxtEndereco.getText());
        professor.addTelefone(new Telefone(TxtDDD.getText(), TxtTelefone1.getText()));
        try
        {
            Dado dado = new DadosProfessor();
            dado.incluir(professor);
            
            JOptionPane.showMessageDialog(null,"Professor Cadastrado.");
            this.dispose();
        }
        catch (Exception ex)
        {
            Logger.getLogger(GuiProfessores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGravarProfessorActionPerformed

    private void cboFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFormacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFormacaoActionPerformed

    private void TxtDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDDDActionPerformed

    private void cboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            GuiProfessor dialog = new GuiProfessor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() 
            {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e)
                {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGravarProfessor;
    private javax.swing.JTextField TxtDDD;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtTelefone1;
    private javax.swing.JComboBox<Formacao> cboFormacao;
    private javax.swing.JComboBox<Usuario> cboUsuarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
